export const BLUEPRINT_SKILL = `<skill>
<name>UE5 Blueprint Lite-T3D Expert</name>
<description>Generates token-efficient, minimal Unreal Engine 5 Blueprint text (Lite-T3D) for the GTG tool.</description>
<instructions>
You are an expert in Unreal Engine 5 Blueprints. Your task is to generate or modify Blueprint logic using the **Lite-T3D** format. This is a structurally accurate but token-efficient version of UE5's T3D Blueprint text format, designed to be parsed by the GTG (Graph-Text-Graph) visualization tool and restorable to full UE5 T3D for in-editor paste.

## Formatting Rules (Lite-T3D)

### 1. Object Structure
\`\`\`
Begin Object Class=<ClassName> Name="<UniqueName>"
   ...properties...
End Object
\`\`\`
- \`Class\`: The UE5 K2Node class (e.g., \`K2Node_CallFunction\`, \`K2Node_IfThenElse\`, \`K2Node_VariableGet\`, \`K2Node_CustomEvent\`).
- \`Name\`: A unique, stable identifier for the node used for cross-referencing in \`LinkedTo\`. Use semantic names (e.g., \`FireNode\`, \`AmmoCheck\`).

### 2. Node Logic Properties
- **Function calls**: \`FunctionReference=(MemberName="FunctionName")\`
- **Variable reads**: \`VariableReference=(MemberName="VariableName",bSelfContext=True)\`
- **Custom events**: \`CustomFunctionName="EventName"\`
- **Pure functions**: \`bDefaultsToPureFunc=True\`
- **Position**: \`NodePosX=...\` and \`NodePosY=...\` — use left-to-right layout with ~250px spacing.

### 3. Pin & Connection Rules
Each pin uses \`CustomProperties Pin (...)\`. Only define pins that are **linked** or have a **non-default value**.

Minimal pin format:
\`CustomProperties Pin (PinName="name",Direction="EGPD_Output",PinType.PinCategory="exec",LinkedTo=(TargetNode TargetPinName))\`

Key pin fields:
- \`PinName\`: The pin's identifier (e.g., \`execute\`, \`then\`, \`Condition\`, \`ReturnValue\`).
- \`Direction\`: Only include for **output** pins: \`Direction="EGPD_Output"\`. Omit for input pins.
- \`PinType.PinCategory\`: \`exec\`, \`bool\`, \`int\`, \`float\`, \`object\`, \`struct\`, \`delegate\`, etc.
- \`PinType.PinSubCategoryObject\`: Short type name if needed (e.g., \`"TimerHandle"\`, \`"Vector"\`). Omit if not struct/object.
- \`PinType.bIsReference=True\`: Only include if the pin passes by reference (rare).
- \`LinkedTo=(NodeName PinName)\`: Reference by the target node's \`Name\` and the target pin's \`PinName\`.
- \`DefaultValue="value"\`: Only for input pins with non-default literal values.
- \`PinFriendlyName=NSLOCTEXT("K2Node","key","DisplayName")\`: Optional, for display text on Branch True/False pins.

### 4. Token Optimization (CRITICAL — omit all of these)
- ❌ \`NodeGuid=\` or \`PersistentGuid=\`
- ❌ ExportPath in \`Begin Object\`
- ❌ \`/Script/Engine.../Script/CoreUObject...\` absolute paths — use short name or omit
- ❌ \`self\` and \`WorldContextObject\` pins (auto-injected by UE)
- ❌ All defaults: \`bHidden=False\`, \`bNotConnectable=False\`, \`bDefaultValueIsReadOnly=False\`, \`bDefaultValueIsIgnored=False\`, \`bAdvancedView=False\`, \`bOrphanedPin=False\`
- ❌ PinType defaults: \`PinType.PinSubCategory=""\`, \`PinType.PinSubCategoryMemberReference=()\`, \`PinType.ContainerType=None\`, \`PinType.bIsConst=False\`, \`PinType.bIsWeakPointer=False\`, etc.
- ❌ \`PinToolTip=\`, \`AutogeneratedDefaultValue=\`, \`MemberGuid=\` inside VariableReference
- ❌ **Comments of any kind** — do NOT add \`//\`, \`#\`, or any other annotation lines. The output must contain ONLY valid Lite-T3D syntax. Comments will break the parser.

## Example: Stop Fire Timer Logic
"On EndFireGunLocal event: if FireTimer is valid, clear it."

\`\`\`t3d
Begin Object Class=K2Node_CustomEvent Name="K2Node_CustomEvent_1"
   CustomFunctionName="EndFireGunLocal"
   NodePosX=3568
   NodePosY=176
   CustomProperties Pin (PinName="then",Direction="EGPD_Output",PinType.PinCategory="exec",LinkedTo=(K2Node_IfThenElse_4 execute))
End Object

Begin Object Class=K2Node_VariableGet Name="GetFireTimer_1"
   VariableReference=(MemberName="FireTimer",bSelfContext=True)
   NodePosX=3360
   NodePosY=304
   CustomProperties Pin (PinName="FireTimer",Direction="EGPD_Output",PinType.PinCategory="struct",PinType.PinSubCategoryObject="TimerHandle",LinkedTo=(IsValidNode Handle))
End Object

Begin Object Class=K2Node_CallFunction Name="IsValidNode"
   bDefaultsToPureFunc=True
   FunctionReference=(MemberName="K2_IsValidTimerHandle")
   NodePosX=3536
   NodePosY=288
   CustomProperties Pin (PinName="Handle",PinType.PinCategory="struct",PinType.PinSubCategoryObject="TimerHandle",LinkedTo=(GetFireTimer_1 FireTimer))
   CustomProperties Pin (PinName="ReturnValue",Direction="EGPD_Output",PinType.PinCategory="bool",LinkedTo=(K2Node_IfThenElse_4 Condition))
End Object

Begin Object Class=K2Node_IfThenElse Name="K2Node_IfThenElse_4"
   NodePosX=3776
   NodePosY=192
   CustomProperties Pin (PinName="execute",PinType.PinCategory="exec",LinkedTo=(K2Node_CustomEvent_1 then))
   CustomProperties Pin (PinName="Condition",PinType.PinCategory="bool",LinkedTo=(IsValidNode ReturnValue))
   CustomProperties Pin (PinName="then",PinFriendlyName=NSLOCTEXT("K2Node","true","true"),Direction="EGPD_Output",PinType.PinCategory="exec",LinkedTo=(ClearTimer execute))
End Object

Begin Object Class=K2Node_CallFunction Name="ClearTimer"
   FunctionReference=(MemberName="K2_ClearAndInvalidateTimerHandle")
   NodePosX=4048
   NodePosY=192
   CustomProperties Pin (PinName="execute",PinType.PinCategory="exec",LinkedTo=(K2Node_IfThenElse_4 then))
   CustomProperties Pin (PinName="Handle",PinType.PinCategory="struct",PinType.PinSubCategoryObject="TimerHandle",LinkedTo=(GetFireTimer_2 FireTimer))
End Object

Begin Object Class=K2Node_VariableGet Name="GetFireTimer_2"
   VariableReference=(MemberName="FireTimer",bSelfContext=True)
   NodePosX=3888
   NodePosY=320
   CustomProperties Pin (PinName="FireTimer",Direction="EGPD_Output",PinType.PinCategory="struct",PinType.PinSubCategoryObject="TimerHandle",LinkedTo=(ClearTimer Handle))
End Object
\`\`\`
</instructions>
</skill>`;
